package com.wipro.qa.stepDefinitions;

// Generated by Selenium IDE
import org.junit.Test;
        import org.junit.Before;
        import org.junit.After;
        import static org.junit.Assert.*;
        import static org.hamcrest.CoreMatchers.is;
        import static org.hamcrest.core.IsNot.not;
        import org.openqa.selenium.By;
        import org.openqa.selenium.WebDriver;
        import org.openqa.selenium.firefox.FirefoxDriver;
        import org.openqa.selenium.chrome.ChromeDriver;
        import org.openqa.selenium.remote.RemoteWebDriver;
        import org.openqa.selenium.remote.DesiredCapabilities;
        import org.openqa.selenium.Dimension;
        import org.openqa.selenium.WebElement;
        import org.openqa.selenium.interactions.Actions;
        import org.openqa.selenium.support.ui.ExpectedConditions;
        import org.openqa.selenium.support.ui.WebDriverWait;
        import org.openqa.selenium.JavascriptExecutor;
        import org.openqa.selenium.Alert;
        import org.openqa.selenium.Keys;
        import java.util.*;
        import java.net.MalformedURLException;
        import java.net.URL;
public class CreateNewProjectTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","src/test/resources/drivers/chromedriver88.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void createNewProject() throws InterruptedException {
        driver.get("https://laminar-sit-ui.azurewebsites.net/");
        driver.manage().window().setSize(new Dimension(1048, 706));
        driver.findElement(By.name("userEmail")).click();
        driver.findElement(By.name("userEmail")).sendKeys("superuser@bv.com");
        driver.findElement(By.name("password")).click();
        driver.findElement(By.name("password")).sendKeys("Test");
        driver.findElement(By.cssSelector(".btn-primary")).click();
        Thread.sleep(3000);
        driver.findElement(By.cssSelector(".create-project")).click();
        driver.findElement(By.name("projectNumber")).click();
        driver.findElement(By.name("projectNumber")).sendKeys("AMR149");
        driver.findElement(By.name("projectName")).click();
        driver.findElement(By.name("projectName")).sendKeys("Project_Card10");
        driver.findElement(By.cssSelector(".modalPrimaryButton")).click();
        Thread.sleep(5000);
        driver.findElement(By.cssSelector(".col-md-3:nth-child(84) .project-name")).click();
        js.executeScript("window.scrollTo(0,0)");
        driver.findElement(By.id("UncontrolledTooltip1")).click();
        {
            WebElement element = driver.findElement(By.id("UncontrolledTooltip1"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector("div:nth-child(2) > div > .form-row > .form-group:nth-child(3)")).click();
        driver.findElement(By.cssSelector(".css-1pahdxg-control .css-1wa3eu0-placeholder")).click();
        driver.findElement(By.id("react-select-12-option-1")).click();
        driver.findElement(By.cssSelector(".css-1pahdxg-control > .css-1hwfws3")).click();
        driver.findElement(By.id("react-select-23-option-2")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(6) div:nth-child(2) > input")).click();
        driver.findElement(By.name("basicProjectData.proposalProjectRiskScore")).click();
        driver.findElement(By.name("basicProjectData.proposalProjectRiskScore")).sendKeys("67");
        driver.findElement(By.name("basicProjectData.proposalProjectRiskLevel")).click();
        driver.findElement(By.name("basicProjectData.proposalProjectRiskLevel")).sendKeys("78");
        driver.findElement(By.name("basicProjectData.facilityTechnology")).click();
        driver.findElement(By.name("basicProjectData.facilityTechnology")).click();
        driver.findElement(By.name("basicProjectData.facilityTechnology")).sendKeys("FacilityTest1");
        driver.findElement(By.name("basicProjectData.client")).click();
        driver.findElement(By.name("basicProjectData.client")).sendKeys("ClientTest");
        driver.findElement(By.cssSelector(".form-group:nth-child(15) div:nth-child(2) > span")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(15) div:nth-child(2) > input")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(16) div:nth-child(2) > input")).click();
        driver.findElement(By.cssSelector(".save-button")).click();
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(3) > .SideMenuListLabel")).click();
        driver.findElement(By.name("generalScopeData.projectTechnicalSpecificationsBy")).click();
        driver.findElement(By.name("generalScopeData.projectCommercialSpecificationsBy")).click();
        driver.findElement(By.name("generalScopeData.frontEndEngineeringDesignCompleted")).click();
        driver.findElement(By.name("generalScopeData.detailedEngineeringByBlack&Veatch")).click();
        driver.findElement(By.name("generalScopeData.procurementByBlack&Veatch")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(6) div:nth-child(1) > span")).click();
        driver.findElement(By.name("generalScopeData.constructionManagement")).click();
        driver.findElement(By.name("generalScopeData.constructionLiason")).click();
        driver.findElement(By.name("generalScopeData.construction")).click();
        driver.findElement(By.name("generalScopeData.constructabilityCoordinator")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(10) div:nth-child(1)")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(10) > .d-flex")).click();
        driver.findElement(By.name("generalScopeData.startup")).click();
        driver.findElement(By.name("generalScopeData.startupSupport")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(12) div:nth-child(2) > input")).click();
        driver.findElement(By.name("generalScopeData.performanceResponsibilityAndGuaranteesByBlack&Veatch")).click();
        driver.findElement(By.name("generalScopeData.performanceResponsibilityAndGuaranteesByBlack&Veatch")).click();
        driver.findElement(By.name("generalScopeData.performanceResponsibilityAndGuaranteesByBlack&Veatch")).sendKeys("PerfTest");
        driver.findElement(By.name("generalScopeData.supplierSubcontractorInvoiceProcessing")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(15) div:nth-child(1)")).click();
        driver.findElement(By.name("generalScopeData.materialsManagementCoordination")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(16) div:nth-child(2) > input")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(20) div:nth-child(2) > input")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(20) div:nth-child(1) > span")).click();
        driver.findElement(By.name("generalScopeData.projectEngineeringManagerRequired")).click();
        driver.findElement(By.name("generalScopeData.projectControlsManagerRequired")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".save-button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".save-button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".save-button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
        driver.findElement(By.cssSelector(".save-button")).click();
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(4) > .SideMenuListLabel")).click();
        driver.findElement(By.cssSelector(".css-1hwfws3")).click();
        driver.findElement(By.id("react-select-235-option-1")).click();
        driver.findElement(By.name("projectTechnicalData.authorityHavingJurisdiction")).click();
        driver.findElement(By.name("projectTechnicalData.authorityHavingJurisdiction")).sendKeys("US");
        driver.findElement(By.cssSelector(".form-group:nth-child(3) div:nth-child(2) > input")).click();
        driver.findElement(By.name("projectTechnicalData.stateRegCode")).click();
        driver.findElement(By.name("projectTechnicalData.stateRegCode")).sendKeys("BVTest");
        driver.findElement(By.name("projectTechnicalData.physicalDesignApproach")).click();
        driver.findElement(By.name("projectTechnicalData.awpUsedOnProject")).click();
        driver.findElement(By.cssSelector(".form-group:nth-child(7) div:nth-child(1)")).click();
        driver.findElement(By.name("projectTechnicalData.modulesOnProject")).click();
        driver.findElement(By.cssSelector(".save-button")).click();
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(5) > .SideMenuListLabel")).click();
        driver.findElement(By.cssSelector(".css-1pahdxg-control .css-1wa3eu0-placeholder")).click();
        driver.findElement(By.id("react-select-259-input")).sendKeys("CostTest");
        driver.findElement(By.cssSelector(".css-1pahdxg-control .css-1wa3eu0-placeholder")).click();
        driver.findElement(By.id("react-select-260-input")).sendKeys("Field");
        driver.findElement(By.cssSelector(".css-1pahdxg-control .css-1wa3eu0-placeholder")).click();
        driver.findElement(By.id("react-select-261-input")).sendKeys("Staffing");
        driver.findElement(By.cssSelector(".css-1pahdxg-control > .css-1hwfws3")).click();
        driver.findElement(By.id("react-select-262-input")).sendKeys("Drawing");
        {
            WebElement element = driver.findElement(By.cssSelector(".save-button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".save-button")).click();
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(6)")).click();
        driver.findElement(By.cssSelector(".css-1pahdxg-control > .css-1hwfws3")).click();
        driver.findElement(By.id("react-select-263-input")).sendKeys("Material");
        driver.findElement(By.cssSelector(".css-1wa3eu0-placeholder")).click();
        driver.findElement(By.id("react-select-264-input")).sendKeys("Procurement");
        {
            WebElement element = driver.findElement(By.cssSelector(".save-button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.cssSelector(".save-button")).click();
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector("#UncontrolledTooltip2 img")).click();
        {
            WebElement element = driver.findElement(By.id("UncontrolledTooltip2"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector("#UncontrolledTooltip2 img"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".form-container > div")).click();
        driver.findElement(By.cssSelector(".addWbsRow")).click();
        driver.findElement(By.name("wbsTable[0].cwaId")).click();
        driver.findElement(By.name("wbsTable[0].cwaId")).sendKeys("CWATest");
        driver.findElement(By.name("wbsTable[0].cwaName")).click();
        driver.findElement(By.name("wbsTable[0].cwaName")).sendKeys("CWANAME");
        driver.findElement(By.cssSelector(".form-container")).click();
        driver.findElement(By.cssSelector(".save-button")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".save-button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".save-button")).click();
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(3)")).click();
        driver.findElement(By.cssSelector(".addWbsRow")).click();
        driver.findElement(By.name("wbsTable[0].moduleNumber")).click();
        driver.findElement(By.name("wbsTable[0].moduleNumber")).sendKeys("ModuleTestNum");
        driver.findElement(By.name("wbsTable[0].moduleName")).sendKeys("ModuleTestName");
        driver.findElement(By.name("wbsTable[0].cwaNumberName")).click();
        {
            WebElement dropdown = driver.findElement(By.name("wbsTable[0].cwaNumberName"));
            dropdown.findElement(By.xpath("//option[. = 'CWATest-CWANAME']")).click();
        }
        driver.findElement(By.name("wbsTable[0].cwaNumberName")).click();
        driver.findElement(By.cssSelector(".save-button")).click();
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(4) > .SideMenuListLabel")).click();
        driver.findElement(By.cssSelector(".form-container > div")).click();
        driver.findElement(By.cssSelector(".addWbsRow")).click();
        driver.findElement(By.name("wbsTable[0].purchaseSpecNumber")).click();
        {
            WebElement dropdown = driver.findElement(By.name("wbsTable[0].purchaseSpecNumber"));
            dropdown.findElement(By.xpath("//option[. = '61.0802']")).click();
        }
        driver.findElement(By.name("wbsTable[0].purchaseSpecNumber")).click();
        driver.findElement(By.name("wbsTable[0].discipline")).click();
        driver.findElement(By.cssSelector(".save-button")).click();
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(5) > .SideMenuListLabel")).click();
        driver.findElement(By.cssSelector(".addWbsRow")).click();
        driver.findElement(By.cssSelector("td:nth-child(1)")).click();
        driver.findElement(By.name("wbsTable[0].processAreaId")).click();
        driver.findElement(By.name("wbsTable[0].processAreaId")).sendKeys("7897");
        driver.findElement(By.name("wbsTable[0].processAreaName")).click();
        driver.findElement(By.name("wbsTable[0].processAreaName")).sendKeys("ProcessAreaTest");
        driver.findElement(By.cssSelector(".save-button")).click();
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector("#UncontrolledTooltip6 img")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("#UncontrolledTooltip6 img"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".field-group:nth-child(1) .custom-control-label")).click();
        driver.findElement(By.cssSelector(".auto-select-prefix-theme__control--is-focused .auto-select-prefix-theme__placeholder")).click();
        driver.findElement(By.id("react-select-267-input")).sendKeys("pip");
        driver.findElement(By.id("react-select-267-input")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector(".mx-2:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".modalPrimaryButton")).click();
        driver.findElement(By.cssSelector(".save-button")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".save-button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".completeButtonActive"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(3) > .SideMenuListLabel")).click();
        driver.findElement(By.cssSelector(".field-group:nth-child(1) .custom-control-label")).click();
        driver.findElement(By.cssSelector(".auto-select-prefix-theme__control--is-focused > .auto-select-prefix-theme__value-container")).click();
        driver.findElement(By.id("react-select-271-input")).sendKeys("Ele");
        driver.findElement(By.id("react-select-271-input")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector(".mx-2:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".modalPrimaryButton")).click();
        driver.findElement(By.cssSelector(".save-button")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".save-button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(4) > .SideMenuListLabel")).click();
        driver.findElement(By.cssSelector(".field-group:nth-child(1) .custom-control-label")).click();
        driver.findElement(By.cssSelector(".auto-select-prefix-theme__control--is-focused .auto-select-prefix-theme__placeholder")).click();
        driver.findElement(By.id("react-select-275-option-3")).click();
        driver.findElement(By.cssSelector(".mx-2:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".modalPrimaryButton")).click();
        driver.findElement(By.cssSelector(".save-button")).click();
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(5) > .SideMenuListLabel")).click();
        driver.findElement(By.cssSelector(".field-group:nth-child(1) .custom-control-label")).click();
        driver.findElement(By.cssSelector(".auto-select-prefix-theme__control--is-focused .auto-select-prefix-theme__placeholder")).click();
        driver.findElement(By.id("react-select-279-option-4")).click();
        driver.findElement(By.cssSelector(".mx-2:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".modalPrimaryButton")).click();
        driver.findElement(By.cssSelector(".save-button")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".save-button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(6) > .SideMenuListLabel")).click();
        driver.findElement(By.cssSelector(".field-group:nth-child(1) .custom-control-label")).click();
        driver.findElement(By.cssSelector(".auto-select-prefix-theme__control--is-focused .auto-select-prefix-theme__placeholder")).click();
        driver.findElement(By.id("react-select-283-option-5")).click();
        driver.findElement(By.cssSelector(".mx-2:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".modalPrimaryButton")).click();
        driver.findElement(By.cssSelector(".save-button")).click();
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(7) > .SideMenuListLabel")).click();
        driver.findElement(By.cssSelector(".field-group:nth-child(1) .custom-control-label")).click();
        driver.findElement(By.cssSelector(".auto-select-prefix-theme__control--is-focused .auto-select-prefix-theme__placeholder")).click();
        driver.findElement(By.id("react-select-287-option-1")).click();
        driver.findElement(By.cssSelector(".mx-2:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".modalPrimaryButton")).click();
        driver.findElement(By.cssSelector(".save-button")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".save-button"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(7)")).click();
        driver.findElement(By.cssSelector(".sidemenu-item:nth-child(8) > .SideMenuListLabel")).click();
        driver.findElement(By.cssSelector(".field-group:nth-child(1) .custom-control-label")).click();
        driver.findElement(By.cssSelector(".auto-select-prefix-theme__control--is-focused .auto-select-prefix-theme__placeholder")).click();
        driver.findElement(By.id("react-select-291-input")).sendKeys("vish");
        driver.findElement(By.id("react-select-291-input")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector(".action-block")).click();
        driver.findElement(By.cssSelector(".mx-2:nth-child(2)")).click();
        driver.findElement(By.cssSelector(".modalPrimaryButton")).click();
        driver.findElement(By.cssSelector(".save-button")).click();
        driver.findElement(By.cssSelector(".completeButtonActive")).click();
        driver.findElement(By.cssSelector("#UncontrolledTooltip3 > .notificationContainer")).click();
        {
            WebElement element = driver.findElement(By.cssSelector("#UncontrolledTooltip3 > .notificationContainer"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.id("UncontrolledTooltip3"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector("#UncontrolledTooltip3 > .notificationContainer"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.name("manhrsTable[0].usEngHours")).click();
        driver.findElement(By.name("manhrsTable[0].usEngHours")).click();
        driver.findElement(By.name("manhrsTable[0].usEngHours")).sendKeys("953685950");
        driver.findElement(By.name("manhrsTable[0].usDsgnHours")).click();
        driver.findElement(By.name("manhrsTable[0].usDsgnHours")).click();
        {
            WebElement element = driver.findElement(By.name("manhrsTable[0].usEngHours"));
            Actions builder = new Actions(driver);
            builder.doubleClick(element).perform();
        }
        driver.findElement(By.name("manhrsTable[0].usEngHours")).sendKeys("5");
        driver.findElement(By.name("manhrsTable[0].usDsgnHours")).sendKeys("6");
        driver.findElement(By.name("manhrsTable[0].ousEngHours")).sendKeys("8");
        driver.findElement(By.name("manhrsTable[0].ousDsgnHours")).click();
        driver.findElement(By.name("manhrsTable[0].ousDsgnHours")).sendKeys("9");
        driver.findElement(By.name("manhrsTable[1].usEngHours")).sendKeys("5");
        driver.findElement(By.name("manhrsTable[1].usDsgnHours")).sendKeys("3");
        {
            WebElement element = driver.findElement(By.id("selenium-ide-indicator"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).clickAndHold().perform();
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".manhrsContainer > div:nth-child(3)"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).release().perform();
        }
    }
}
